# Loads all Homelab support

# Do nothing if not running interactively
[[ -n $PS1 ]] || return

CONFIG_DIR="$HOME/.config/homelab"
CONFIG_FILE="$CONFIG_DIR/homelab.conf"
ENV_FILE="$CONFIG_DIR/homelab.env"

runElevated() {
    [[ $EUID != 0 ]] && sudo "$@" || "$@"
}

cdhl() {
        # Change to homelab directory, wherever it is
        if [[ -d ~/homelab ]]; then
                cd ~/homelab
        elif [[ -d /mnt/homelab ]]; then
                cd /mnt/homelab
        fi
}

cdhp() {
        # Change to homelab directory
        if [[ -d ~/homelab_priv ]]; then
                cd ~/homelab_priv
        fi
}

getPackageManager() {
        # Determine Package Manager
        local packageManagers=(
                apt
                dnf
        )

        for packageManager in "${packageManagers[@]}"; do
                if command -v $packageManager &>/dev/null; then
                        echo $packageManager
                        return
                fi
        done
}

initializeHomelab() {

        # Check for existence of config directory
        if [[ ! -d "$(dirname $CONFIG_FILE)" ]]; then
                mkdir -p "$(dirname $CONFIG_FILE)"
        fi

        # Check for existence of the config file
        if [[ ! -f "$CONFIG_FILE" ]]; then
                # Add default set of applications to new config
                jq -n '{
                        allApps: ["ncdu","eza","bat"],
                        aptApps: ["screenfetch"],
                        dnfApps: ["fastfetch"]
                }' > "$CONFIG_FILE"
                echo "Homelab config file created: $CONFIG_FILE"
        fi
}

installApps() {
        local packageManager=$(getPackageManager)
        local requiredApps=()

        if [[ -z $packageManager ]]; then
                echo "No supported package managers found. Nothing will be installed."
                return 1
        fi

        if [[ $packageManager == "apt" ]]; then
                installedApps="$(apt list --installed 2>/dev/null)"
                mapfile -t requiredApps < <(jq -r '.allApps[] , .aptApps[]' "$CONFIG_FILE")
        elif [[ $packageManager == "dnf" ]]; then
                installedApps="$(dnf list installed 2>/dev/null)"
                mapfile -t requiredApps < <(jq -r '.allApps[] , .dnfApps[]' "$CONFIG_FILE")
        fi

        local repositoryUpdated=''
        for app in "${requiredApps[@]}"; do

                # Does app show up in list of installed apps
                if echo "$installedApps" | grep "^$app[/\.]" >/dev/null 2>&1; then
                        continue
                fi

                # Install missing packages
                case $packageManager in
                apt)
                        if [[ $repositoryUpdated != 'y' ]]; then
                                echo "App installation required. Updating repositories..."
                                runElevated apt update -q 2>&1 | grep -v "WARNING: apt does not have a stable CLI interface" >/dev/null
                                repositoryUpdated='y'
                        fi
                        echo "Installing $app..."
                        runElevated apt install -y $app 2>&1 | grep -v "WARNING: apt does not have a stable CLI interface" >/dev/null
                        ;;
                dnf)
                        if [[ $repositoryUpdated != 'y' ]]; then
                                echo "App installation required. Updating repositories..."
                                runElevated dnf update -q -y
                                runElevated dnf install epel-release -q -y
                                repositoryUpdated='y'
                        fi
                        echo "Installing $app..."
                        runElevated dnf install -y $app 2>&1
                        ;;
                *)
                        echo "Unknown package manager: $packageManager"
                        ;;
                esac
        done

}

initializeHomelab
installApps

# set PATH so it includes homelab scripts
if [[ -d "$HOME/scripts" ]] ; then
        PATH="$HOME/scripts:$PATH"
fi

# Make sure there is a nano backup directory
if [[ ! -d "$HOME/.nanobackup" ]]; then
        mkdir "$HOME/.nanobackup"
fi

# Environment
export EDITOR="nano"
export GREP_COLOR='1;36'
export HISTCONTROL='ignoredups'
export HISTSIZE=5000
export HISTFILESIZE=5000
export PAGER='less'
export TZ='America/Chicago'
export GIT_DEFAULT_BRANCH="main"

if [[ -f ${ENV_FILE} ]]; then
        source ${ENV_FILE}
fi

# Shell options
shopt -s cdspell
shopt -s checkwinsize
shopt -s autocd   2>/dev/null || true
shopt -s dirspell 2>/dev/null || true

# Aliases
alias ..='echo "cd .."; cd ..'
alias ...='echo "cd ../.."; cd ../..'
alias ....='echo "cd ../../.."; cd ../../..'
alias whereami='curl -sSf --connect-timeout 1 https://ipinfo.io/city 2>/dev/null || echo "NO CONNECTION"'
alias l='ls'
alias ll='ls -hAlF'
alias flushdns='resolvectl flush-caches'
alias update-all='runElevated apt update && runElevated apt upgrade -y'
grep --color=auto < /dev/null &>/dev/null && alias grep='grep --color=auto'

if command -v batcat >/dev/null 2>&1; then
        alias bat='batcat'
fi

if command -v ncdu >/dev/null 2>&1; then
        alias du='ncdu -x -e --color dark'
fi

if command -v eza >/dev/null 2>&1; then
        alias ls='eza --group-directories-first --icons'
else
        alias ls='ls --group-directories-first --color=auto'
        eval $(dircolors -b)
fi

# Show system info
command -v screenfetch >/dev/null && screenfetch
command -v fastfetch >/dev/null && fastfetch

# Check filesystem usage
if [[ -f "$HOME/scripts/check-freespace.sh" ]]; then
        echo
        $HOME/scripts/check-freespace.sh 75
fi

source ~/scripts/fancy-prompt.sh

# Report location
echo Welcome to $(whereami)!
